### ISSUE TITLE
vscode extension

### ISSUE THREAD

**Issue by taizod1024** [taizod1024/ac-ts-cli#17]

**Comment by taizod1024** [comment]
plantuml test
```plantuml
@startuml
aaa -> bbb
@enduml
```

**Comment by taizod1024** [comment]
```
yo code
```
で以下のエラーが発生。調査中。
```
C:\Users\taizo\AppData\Roaming\npm\node_modules\yo\node_modules\editions\edition-es5\index.js:317
				throw util_js_1.errtion(
				^

Error: editions-autoloader-none-broadened: Unable to determine a suitable edition, even after broadening.
    at new Errlop (C:\Users\taizo\AppData\Roaming\npm\node_modules\yo\node_modules\errlop\edition-es5\index.js:61:18)
    at Object.errtion (C:\Users\taizo\AppData\Roaming\npm\node_modules\yo\node_modules\editions\edition-es5\util.js:23:14)
    at determineEdition (C:\Users\taizo\AppData\Roaming\npm\node_modules\yo\node_modules\editions\edition-es5\index.js:317:21)
    at solicitEdition (C:\Users\taizo\AppData\Roaming\npm\node_modules\yo\node_modules\editions\edition-es5\index.js:350:16)
    at Object.requirePackage (C:\Users\taizo\AppData\Roaming\npm\node_modules\yo\node_modules\editions\edition-es5\index.js:364:9)
    at Object.<anonymous> (C:\Users\taizo\AppData\Roaming\npm\node_modules\yo\node_modules\istextorbinary\index.cjs:4:38)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
```

**Comment by taizod1024** [comment]
https://github.com/electron-userland/electron-builder/issues/5668#issuecomment-823621448

node.jsを15.40に下げることで解決かも

**Comment by taizod1024** [comment]
> [electron-userland/electron-builder#5668 (comment)](https://github.com/electron-userland/electron-builder/issues/5668#issuecomment-823621448)
> 
> node.jsを15.40に下げることで解決かも

```
choco uninstall nodejs
choco install nodejs --version 15.14.0
```

**Comment by taizod1024** [comment]
> > [electron-userland/electron-builder#5668 (comment)](https://github.com/electron-userland/electron-builder/issues/5668#issuecomment-823621448)
> > node.jsを15.40に下げることで解決かも
> 
> ```
> choco uninstall nodejs
> choco install nodejs --version 15.14.0
> ```

nodejsを除外してアップグレード
```
choco upgrade all --except nodejs
```

**Comment by taizod1024** [comment]
`yo code`でコードを生成
各コンフィグをマージ
node_modulesとpackage-lock.jsonを削除してから`npm install`で再生成

**Comment by taizod1024** [comment]
package.jsonを修正
Run Extensionでデバッグ
